export const GET_SCORE_BY_STUDENT_ID = "GET_SCORE_BY_STUDENT_ID";
export const GET_SCORE_BY_STUDENT_ID_SUC = "GET_SCORE_BY_STUDENT_ID_SUC";
export const SET_SCORE_EDITING = "SET_SCORE_EDITING";
export const SAVE_SCORE_STUDENT = "SAVE_SCORE_STUDENT";
export const SAVE_SCORE_STUDENT_SUC = "SAVE_SCORE_STUDENT_SUC";
