export const GET_STUDENT_CLASS = "GET_STUDENT_CLASS";
export const GET_STUDENT_CLASS_SUC = "GET_STUDENT_CLASS_SUC";
export const SET_STUDENT_CLASS_EDITING = "SET_STUDENT_CLASS_EDITING";
export const SAVE_STUDENT_CLASS = "SAVE_STUDENT_CLASS";
export const SAVE_STUDENT_CLASS_SUC = "SAVE_STUDENT_CLASS_SUC";
export const DELETE_STUDENT_CLASS = "DELETE_STUDENT_CLASS";
export const DELETE_STUDENT_CLASS_SUC = "DELETE_STUDENT_CLASS_SUC";
