export const GET_ALL_SUBJECT = "GET_ALL_SUBJECT";
export const GET_ALL_SUBJECT_SUC = "GET_ALL_SUBJECT_SUC";
export const SAVE_SUBJECT = "SAVE_SUBJECT";
export const SAVE_SUBJECT_SUC = "SAVE_SUBJECT_SUC";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const DELETE_SUBJECT_SUC = "DELETE_SUBJECT_SUC";
export const SET_SUBJECT_EDITING = "SET_SUBJECT_EDITING";
